<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <style type="text/css">
         *{
         text-decoration:none;
         padding:0px;
         list-style:none;
     box-sizing:border-box;
         }
      </style>
   </head>
   <body  bgcolor="#fff" style="margin: 0; padding: 0; min-width: 100%!important;">
      <table width="100%" style="font-family: sans-serif;"  border="0" cellpadding="0" cellspacing="0">
         <tr>
            <td>
               <table style="width: 100%; max-width: 910px;   box-shadow: 0 3px 14px rgba(0, 0, 0, 0.3); margin:30px auto; padding:10px 15px;" align="center" cellpadding="0" cellspacing="0" border="0">
                  <tr style="">
                     <td>
                        <table style="padding:19px; margin-bottom:20px; background: #f9f9f9; border:1px solid #f1f1f1; border-radius:4px;" width="100%" cellpadding="0" cellspacing="0">
                           <tr>
                           <td>
                              <table width="100%" cellpadding="0" cellspacing="0" >
<tr style="text-transform:uppercase;">
<td>
<p style="margin-top:0px; font-weight:500; line-height:24px; color:#333; font-size:15px; letter-spacing:0.4px; text-transform:none; "><b>Dear MR. MARVEN LESIBA MATSHA</b></p>
</td>
</tr>
<tr style="text-transform:uppercase;">
<td>
<p style="margin-top:0px; font-weight:500; line-height:28px; color:#333; font-size:15px; letter-spacing:0.2px; text-transform:none; padding:10px 4px;">
 Your USER PROFILE had been created on the TUT WIL MANAGEMENT AND TRACKING SYSTEMS as follows:
</p>
</td>
</tr>
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse: separate; border-spacing: 0px 10px; margin:0px auto;">
<tr style="">
<td width="30%">
<p style="margin:0px 0px 0px 0px; font-size:14px; text-transform:uppercase; color:#333; font-weight:600;">NAME :
</p>
</td>
<td width="70%">
<p style="margin:0px; padding-left:8px; color:#666; font-size:14px; font-weight:600;">MR. MARVEN LESIBA MATSHA</p>
</td>
</tr>

<tr>
<td width="30%">
<p style="margin:0px 0px 0px 0px; font-size:14px; color:#333; text-transform:uppercase; font-weight:600;">Email :
</p>
</td>
<td width="70%">
<p style="margin:0px; padding-left:8px; color:#666; font-size:14px; font-weight:600;">getemsiba@gmail.com</p>
</td>
</tr>

<tr>
<td width="30%">
<p style="margin:0px 0px 0px 0px; font-size:14px; color:#333; text-transform:uppercase; font-weight:600;">Mobile :
</p>
</td>
<td width="70%">
<p style="margin:0px; padding-left:8px; color:#666; font-size:14px; font-weight:600;">0818326244</p>
</td>
</tr>

<tr>
<td width="30%">
<p style="margin:0px 0px 0px 0px; font-size:14px; color:#333; text-transform:uppercase; font-weight:600;">DEPARTMENT :
</p>
</td>
<td width="70%">
<p style="margin:0px; padding-left:8px; color:#666; font-size:14px; font-weight:600;">NATURE CONSERVATION</p>
</td>
</tr>

<tr>
<td width="30%">
<p style="margin:0px 0px 0px 0px; font-size:14px; color:#333; text-transform:uppercase; font-weight:600;">FACULTY :
</p>
</td>
<td width="70%">
<p style="margin:0px; padding-left:8px; color:#666; font-size:14px; font-weight:600;">FACULTY OF SCIENCE</p>
</td>
</tr>

<tr>
<td width="30%">
<p style="margin:0px 0px 0px 0px; font-size:14px; color:#333; text-transform:uppercase; font-weight:600;">CAMPUS :
</p>
</td>
<td width="70%">
<p style="margin:0px; padding-left:8px; color:#666; font-size:14px; font-weight:600;">PRETORIA CAMPUS</p>
</td>
</tr>

</table>
</td>
</tr>
<table width="100%" cellpadding="0" cellspacing="0" style="margin-top:15px;">

<tr>
<td>
 <br>
 <br>
<table width="100%" cellpadding="0" cellspacing="0" style="border-collapse: separate; border-spacing: 0px 10px; margin:0px auto;">
<tr style="">
<td width="30%">
<p style="margin:0px 0px 0px 0px; font-size:14px; text-transform:uppercase; color:#333; font-weight:600;">USERNAME :
</p>
</td>
<td width="70%">
<p style="margin:0px; padding-left:8px; color:#666; font-size:14px; font-weight:600;">getemsiba@gmail.com</p>
</td>
</tr>

</table>

</td>
</tr>
<tr>
<td>
<p style="margin-top:0px; font-weight:500; line-height:28px; color:#333; font-size:15px; letter-spacing:0.2px; text-transform:none; padding:10px 4px;">
 TO CREATE YOUR PASSWORD, CLICK ON THE LINK BELOW
</p>
 <p style="margin:0px; padding-left:8px; font-size:14px;">
 <a href="http://tut-wil.local/generate-password/83608590/1877" style="width:100%; text-align:center;margin-top: 20px;margin-bottom: 20px; line-height:24px; display:block; padding:6px 12px; font-size-adjust: 0.5; border:none; font-family:Arial; color:#fff; font-weight:500; text-transform:uppercase; background:#0C7ABF;">CREATE PASSWORD</a>
 
 </p>
 <p style="margin-top:0px; font-weight:500; line-height:28px; color:#333; font-size:15px; letter-spacing:0.2px; text-transform:none; padding:10px 4px;">
 If you require any assistance, please feel free to use the
 <a href="http://tut-wil.local/add-ticket-guest" style=" text-transform:uppercase; "> CONTACT US</a>
 
 Menu on the WIL PORTAL. The WIL ADMINISTRATOR will promptly respond to your query.
</p>
</td>
</tr>

</table>
</td>
</tr>
<tr>
<td>
<table width="100%" cellpadding="0" cellspacing="0" style="margin-top:15px;">

<tr> 
 <td style=""> 
     <p style=" color:#333; font-size:18px; margin:0px 0px 10px; font-weight:500;">Wil Admin</p>
 </td>
</tr>
<tr> 
    <td> 
        <p style="margin:0px 0px 10px; color:#333; font-size:16px; font-weight:600;">TSHWANE UNIVERSITY OF TECHNOLOGY</p> 
    </td>
</tr> 
<tr>
    <td> 
        <p style="margin:0px 0px 10px; color:#333; font-size:15px;"><span style="margin-right:10px; font-weight:600;">Tel :</span>0635633735 </p>
    </td>
</tr> 

<tr> 
    <td>
        <p style=" color:#333; font-size:15px; margin:0px 0px 10px; "><span style="margin-right:10px; font-weight:600;"></span><a style="color:#489FDF
 ; text-decoration:underline;" href=""></a></p>
    </td> 
</tr> 
<tr style='display-flex;justify-content:space-around;'> 
    <td> 
        <p style = "margin-top:20px">
            <a href="">
                <img border="0" src="http://tut-wil.local/img/12/tut_logo.png" alt="" width = "170px" style ="maring-top:20px"/> 
            </a>
        </p> 
    </td>
    <td> 
        <p style = "margin-top:20px;float: right;"> <a href="">
                <img border="0" src="http://tut-wil.local/img/olums_logo.png" alt="" width = "170px" style ="maring-top:20px;"/>
            </a> 
        </p>
    </td>
</tr> 

</table>
 <p style="color:#000000; font-size:10px;margin-top:10px; line-height:20px; font-family: Verdana, Geneva, sans-serif;padding: 10px;">
 The TSHWANE UNIVERSITY OF TECHNOLOGY shall endeavor to ensure the integrity and confidentiality of personal information are protected at all times. However, the Portal shall not be held liable for any inaccurate or false information provided by any User of the System. The content of this email is intended for the exclusive use of the addressee to whom this email was addressed. It shall, at all times, remain private and confidential and the exclusive property of the TSHWANE UNIVERSITY OF TECHNOLOGY. Users are not allowed to share any content of this email with any third party without the consent of TSHWANE UNIVERSITY OF TECHNOLOGY. If this email had been sent to you in error, please delete the email immediately upon receipt. The TSHWANE UNIVERSITY OF TECHNOLOGY reserves its right to take whatever action necessary to protect the information's integrity and confidentiality. 
 </p>
   <p style="color:#000000; font-size:10px;margin-top:10px; line-height:20px;  font-family: Verdana, Geneva, sans-serif;border: 1px solid black;padding: 10px;">
        <b>Protection of Personal Information Act</b> 
        <br>
        These conditions apply equally to all person/s who receive the Personal Information of Students and Graduates.
        <br>
        All Student and Graduate Personal Information, including CVs that the TSHWANE UNIVERSITY OF TECHNOLOGY shares, is strictly confidential. All confidential Personal Information is specifically for the explicit attention of the person/s to whom the correspondence had been addressed and is intended for the sole purpose of the recruitment of Students and/or Graduates and the management of Work Integrated Learning students.
        <br>
        Student and Graduate confidential information can only be shared with the Employer’s Recruitment Personnel, who are directly involved with the respective Recruitment and the Management of Work Integrated Learning processes.
Under no circumstances whatsoever is any person/s allowed to share the Personal Information of Students and Graduates with any unauthorized person/s who are not directly involved with the Recruitment and Work Integrated Learning Management Processes for which the information had been shared by TSHWANE UNIVERSITY OF TECHNOLOGY.
Save for the Employer’s Recruitment Personnel, Mentors and other persons related to the management of Work Integrated Learning Students, it is a criminal offense for any other unauthorized person to receive, and/or be in possession of, and/or to use, and/or to process any Personal Information of Students and Graduates that had been shared by the TSHWANE UNIVERSITY OF TECHNOLOGY. All Personal Information that had been illegally obtained must be deleted/destroyed from all records immediately upon receipt.
        <br>
        All confidential Personal Information of unsuccessful Students and/or Graduates that had been shared with the Employer, including hard and soft copies of CVs, must be deleted/destroyed from all Computers and/or Storage devices and/or Filing Cabinets within seven (7) days after the respective Post/s for which the Candidates had been shared, had been filled.
    </p>
</td> 
</tr> 
</table>
</td> </tr> 
 
</table>
</table></body></html>
